#; -*-makefile-*-
CPP := g++-4.5
#CPP := g++

#CFLAGS := -O3 -g -I. -std=c++0x -march=native -mtune=native
CFLAGS := -O3 -I. -std=c++0x -march=native -mtune=native
CPPFLAGS := ${CFLAGS} 
LIBS :=
LDFLAGS :=
